server:
  port: 8084

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shopsphere?currentSchema=shopsphere_orders
    username: shopsphere
    password: shopsphere
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS shopsphere_orders

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: shopsphere_orders
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.shopsphere.orderservice: DEBUG
    org.hibernate.SQL: DEBUG
