-- V1: Baseline — the notifications table as Hibernate generated it before Flyway.
-- Existing databases are baselined at V1 and skip this file; fresh databases run it.

CREATE TABLE IF NOT EXISTS notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(30)   NOT NULL
        CHECK (type IN ('ORDER_PLACED', 'PAYMENT_SUCCESSFUL', 'PAYMENT_FAILED', 'LOW_STOCK_ALERT')),
    user_id         BIGINT,
    subject         VARCHAR(200)  NOT NULL,
    body            VARCHAR(2000) NOT NULL,
    order_id        BIGINT,
    source_event_id VARCHAR(36)   NOT NULL,
    delivery_status VARCHAR(20)   NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_notifications_user       ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_type       ON notifications (type);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications (created_at);
